concurrent = 1
log_level = "warning"

[[runners]]
  name = "gitlab-ci runner on gitlab host"
  limit = 1
  executor = "docker"
  [runners.docker]
    image = "debian:sid"
    cap_add = ["SYS_ADMIN", "MKNOD"]
    privileged = true
