variables:
    BASE_DISTROS: 'buster bullseye sid'
    ARCHS: 'amd64 arm64 armhf'
    DOCKER_BUILDKIT: '1'
    DOCKER_CLI_EXPERIMENTAL: 'enabled'

stages:
    - build
    - register
    - test
    - push

build-rootfs:
    stage: build
    image: microdeb/bullseye
    artifacts:
        paths:
            - "*.tar.xz"
    rules:
        - if: '$DOCKER_HUB_USER =~ /.+/ && $DOCKER_HUB_ACCESS_TOKEN =~ /.+/ && $DOCKER_HUB_PASS =~ /.+/'
          when: on_success
    script: |
        set -e
        apt-get -y update
        apt-get -y install dirmngr gnupg pixz wget ca-certificates curl \
          gnupg-agent qemu-user-static debootstrap
        for distro in $BASE_DISTROS; do
            ./bootstrap.sh $distro
        done

build-docker-images:
    stage: register
    image: docker:latest
    services:
        - docker:dind
    before_script:
      - BUILDX_URL=$(docker run --rm python:rc-alpine sh -c "pip install --quiet lastversion && lastversion --assets --filter linux-amd64 buildx")
      - mkdir -p $HOME/.docker/cli-plugins/
      - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
      - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    dependencies:
        - build-rootfs
    artifacts:
        paths:
            - "*.conf"
    script: |
        set -e
        echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
        apk update
        apk add git bash tar pixz
        echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
        for distro in $BASE_DISTROS; do
            ./container-build.sh $distro
        done

test-docker-images:
    stage: test
    image: docker:latest
    services:
      - name: docker:dind
        command: ["--experimental"]
    dependencies:
        - build-docker-images
    script: |
        set -e
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
        for architecture in $ARCHS; do
          case "${architecture}" in
            amd64) platform="linux/amd64"; plataforma="x86_64" ;;
            arm64) platform="linux/arm64"; plataforma="aarch64" ;;
            armhf) platform="linux/arm/7"; plataforma="armv7l" ;;
          esac
          for distro in $BASE_DISTROS; do
              . ./${architecture}-${distro}.conf || true
              docker pull --platform $platform $CI_REGISTRY_IMAGE/$IMAGE:$VERSION
              TEST_ARCH=$(docker run --rm $CI_REGISTRY_IMAGE/$IMAGE:$VERSION uname -m)
              if [[ "${plataforma}" == "$TEST_ARCH" ]]; then
                echo "OK Architecture correct"
              else
                echo "Error: Architecture incorrect"
                exit 1
              fi
          done
        done

push-docker-images:
    stage: push
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build-docker-images
    script: |
        set -e
        apk update
        apk add curl jq gawk
        # Push images Docker Hub
        for distro in $BASE_DISTROS; do
            ./docker-push.sh $distro
        done
        #
        # Clean tags.
        for distro in $BASE_DISTROS; do
          ./docker-cleanup.sh $distro
        done
        #
        # Update README and short description.
        # Short Description
        buster_short="Debian Buster slim version for docker"
        bullseye_short="Debian Bullseye slim version for docker"
        sid_short="Debian Sid slim version for docker"
        for distro in $BASE_DISTROS; do
          case "$distro" in
            buster) SHORT=$buster_short ;;
            bullseye) SHORT=$bullseye_short ;;
            sid) SHORT=$sid_short ;;
          esac
          docker run --rm \
            -v "$(pwd)"/README.md:/data/README.md \
            -e DOCKERHUB_USERNAME="$DOCKER_HUB_USER" \
            -e DOCKERHUB_PASSWORD="$DOCKER_HUB_PASS" \
            -e DOCKERHUB_REPO_PREFIX="$DOCKER_HUB_ORGANIZATION" \
            -e DOCKERHUB_REPO_NAME="$distro" \
            -e SHORT_DESCRIPTION="$SHORT" \
            frangal/readme-dockerhub
        done
